version: "2.0"
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
    volumes:
      - .:/app
      - /app/node_modules
  unit_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "test"]
